enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced eXtended MNML"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"                                                   
excluded-patches = "'Alternative thumbnails' 'Append time stamps information' 'Change player flyout panel toggles' 'Change start page' 'Custom branding icon YouTube' 'Custom branding name YouTube' 'Custom double tap length' 'Default playback speed' 'Disable HDR video' 'Enable bottom player gestures' 'Enable compact controls overlay' 'Enable language switch' 'Enable seekbar tapping' 'Enable tablet navigation bar' 'Force OPUS codec' 'Force video codec' 'Hide cast button' 'Hide description components' 'Hide end screen cards' 'Hide fullscreen panels' 'Hide latest videos button' 'Hide load more button' 'Hide seekbar' 'Hide snack bar' 'Hide time stamp' 'Layout switch' 'Premium heading' 'Spoof app version' 'Spoof device dimensions' 'Spoof player parameters' 'Translations'"                                                 
included-patches = "'Add splash animation' 'Enable song search' 'Hide animated button background' 'Hide double tap overlay filter' 'Hide player button background' 'Shorts outline button'"                                                 
version = "auto"                                                      
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx-mnml"

[Music]
build-mode = "both"
app-name = "YouTube-Music"
excluded-patches = "'Change start page' 'Custom branding icon YouTube Music' 'Custom branding name YouTube Music' 'Custom playback speed' 'Enable custom filter' 'Enable playback speed' 'Enable zen mode' 'Hide button shelf' 'Hide carousel shelf' 'Hide cast button' 'Hide category bar' 'Hide fullscreen share button' 'Hide history button' 'Hide playlist card' 'Remember playback speed' 'Replace dismiss queue' 'Spoof app version' 'Translations'"
included-patches = "'Replace cast button'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx-mnml"
arch = "arm64-v8a"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
version = "auto"
