parallel-jobs = 1
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced eXtended MNML"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "alternative-thumbnails append-time-stamps-information change-homepage custom-branding-youtube-name custom-branding-icon-revancify-blue custom-double-tap-length custom-package-name custom-speed-overlay default-playback-speed disable-hdr-video enable-compact-controls-overlay enable-seekbar-tapping enable-tablet-navigation-bar force-opus-codec force-vp9-codec header-switch hide-cast-button hide-description-components hide-end-screen-cards hide-fullscreen-panels hide-latest-videos-button hide-load-more-button hide-player-button-background hide-seekbar hide-snack-bar hide-time-stamp language-switch layout-switch spoof-app-version spoof-player-parameters translations"                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "add-splash-animation force-hide-player-button-background hide-double-tap-overlay-filter"                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx-mnml"

[Music]
build-mode = "both"
app-name = "YouTube-Music"
excluded-patches = "custom-branding-music-name custom-branding-icon-revancify-blue custom-package-name custom-playback-speed enable-custom-filter enable-playback-speed enable-zen-mode hide-button-shelf hide-carousel-shelf hide-cast-button hide-category-bar hide-playlist-card hide-radio-button remember-playback-speed replace-dismiss-queue spoof-app-version start-page translations"
included-patches = "custom-branding-icon-mmt replace-cast-button"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx-mnml"
apkmirror-arch = "arm64-v8a"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
version = "auto"
