enable-module-update = true # set this to false if you do not want to receive updates for the module
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe MNML"
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
version = "auto"
included-patches = "'Change package name'"
excluded-patches = "'Alternative thumbnails' 'Change form factor' 'Change header' 'Change start page' 'Disable double tap actions' 'Disable haptic feedback' 'Disable rolling number animations' 'Disable video codecs' 'Double tap to seek' 'Enable debugging' 'Hide end screen cards' 'Hide info cards' 'Hide related videos' 'Hide timestamp' 'Open Shorts in regular player' 'Open videos fullscreen' 'Reload video' 'Shorts autoplay' 'Spoof device dimensions'"
patcher-args = "-e 'Change package name' -OpackageName=yt.morphe.mnml.noname.exe -e 'Theme' -OdarkThemeBackgroundColor=@android:color/system_neutral1_900"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
module-prop-name = "yt-morphe-mnml"

[Music]
build-mode = "both"
app-name = "YouTube-Music"
version = "auto"
arch = "arm64-v8a"
included-patches = "'Change package name'"
excluded-patches = "'Enable debugging'"
patcher-args = "-e 'Change package name' -OpackageName=ytm.morphe.mnml.noname.exe -e 'Theme' -OdarkThemeBackgroundColor=@android:color/system_neutral1_900"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-morphe-mnml"
