enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced eXtended MNML"
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
included-patches = "'Force hide player buttons background' 'Hide Shorts dimming' 'MaterialYou' 'Return YouTube Username'"
excluded-patches = "'Alternative thumbnails' 'Change start page' 'Custom double tap length' 'Enable debug logging' 'Layout switch' 'Theme' 'Translations for YouTube'"
version = "auto"                                                      
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx-mnml"

[Music]
build-mode = "both"
app-name = "YouTube-Music"
included-patches = "'Custom header for YouTube Music' 'Hide player overlay filter' 'Return YouTube Username'"
excluded-patches = "'Change start page' 'Custom branding name for YouTube Music' 'Enable debug logging' 'Translations for YouTube Music'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx-mnml"
arch = "arm64-v8a"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
version = "auto"
excluded-patches = "'Hide recommended communities shelf' 'Premium icon'"